image: hipex/deploy:v2.12.0-alpha.5-php7.4-node12

variables:
    DOCKER_DRIVER: overlay2
    GIT_DEPTH: 5

stages:
    - build
    - deploy

.template_deployment: &template_deployment
    stage: deploy
    script:
        - hipex-deploy deploy $CI_ENVIRONMENT_NAME -vvv

build:
    stage: build
    script:
        - composer self-update --2
        - wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && mv jq-linux64 /bin/jq && chmod +x /bin/jq
        - hipex-deploy build -vvv
    artifacts:
        paths:
            - build/**

deploy_production:
    environment:
        name: production
        url: https://shopware.bluebirdday.io
    <<: *template_deployment
    when: manual
